# Site settings
title: SnowyPeak Studio
email: how-about@no.com
description: > # this means to ignore newlines until "baseurl:"
  Nope
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sirepi.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  SirePi

# Build settings
markdown: kramdown
